name: Deploy prod site

on: workflow_dispatch

jobs:
  web-deploy:
    name: Deploy Angular portfolio
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 16 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install NPM Modules
      run: yarn install

    - name: Build Project
      run: yarn build:prod

    - name: Deploy Project
      run: yarn deploy:prod
      env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}